#!/usr/bin/env bash
# =============================================================================
# lib/policy.sh - per-user authentication policy store + the OpenVPN-side
# enforcement artifacts (policy file, auth-policy.sh, pam-allow-empty.sh).
#
# The policy file maps every VPN user (certificate CN) to the authentication
# mode that certificate MUST present, and carries the globally allowed modes:
#
#     allowed cert password_totp
#     default cert
#     user alice cert
#     user john password_totp
#
# It intentionally contains NO secrets (usernames and mode names only) and is
# world-readable (0644) inside /etc/openvpn/server: auth-policy.sh runs as
# OpenVPN's unprivileged user ('nobody') and must be able to read it there.
# Actual credential verification happens in the privileged PAM plugin; this
# layer only enforces WHICH factors a certificate must present, that the
# login username equals the certificate CN, and the global allowed-modes
# list. Everything here fails CLOSED. See docs/AUTHENTICATION.md.
# =============================================================================

: "${OVM_POLICY_FILE:=/etc/openvpn/server/auth-policy.conf}"
: "${OVM_POLICY_SCRIPT:=/etc/openvpn/server/auth-policy.sh}"
: "${OVM_PAM_EMPTY_SCRIPT:=/etc/openvpn/server/pam-allow-empty.sh}"
readonly OVM_POLICY_FILE OVM_POLICY_SCRIPT OVM_PAM_EMPTY_SCRIPT

# PAM gate groups: membership decides which credential modules run for a
# user inside the single generated /etc/pam.d/openvpn stack.
readonly OVM_GRP_PASSWORD="ovm-password"
readonly OVM_GRP_TOTP="ovm-totp"
readonly OVM_GRP_YUBIKEY="ovm-yubikey"

policy_ready() { [[ -f "$OVM_POLICY_FILE" ]]; }

# -----------------------------------------------------------------------------
# Policy file read/write (atomic, backed up, validated input only)
# -----------------------------------------------------------------------------

policy_user_mode() { # policy_user_mode <user> -> prints mode; rc=1 if no entry
    local m
    m="$(awk -v u="$1" '$1=="user" && $2==u {print $3; exit}' "$OVM_POLICY_FILE" 2>/dev/null)"
    [[ -n "$m" ]] || return 1
    printf '%s' "$m"
}

policy_list_users() { # -> one "name mode" pair per line
    awk '$1=="user" {print $2, $3}' "$OVM_POLICY_FILE" 2>/dev/null
}

_policy_rewrite() { # _policy_rewrite <user|""> <mode|remove|"">
    # Regenerates the whole file: header from the in-memory config, existing
    # user entries preserved, one optional entry updated/removed. Atomic.
    local upd_user="${1:-}" upd_mode="${2:-}" tmp name mode
    local existing
    existing="$(policy_list_users)"
    backup_file "$OVM_POLICY_FILE"
    mkdir -p "$(dirname "$OVM_POLICY_FILE")"
    tmp="$(mktemp "${OVM_POLICY_FILE}.XXXXXX")" || return 1
    {
        echo "# Generated by openvpn-manager - per-user authentication policy."
        echo "# Contains NO secrets (usernames + required mode only). Do not edit:"
        echo "# it is regenerated on every authentication change."
        echo "allowed ${AUTH_ALLOWED_MODES:-cert}"
        echo "default ${AUTH_DEFAULT_MODE:-cert}"
        while read -r name mode; do
            [[ -z "$name" || "$name" == "$upd_user" ]] && continue
            echo "user ${name} ${mode}"
        done <<< "$existing"
        if [[ -n "$upd_user" && -n "$upd_mode" && "$upd_mode" != "remove" ]]; then
            echo "user ${upd_user} ${upd_mode}"
        fi
    } > "$tmp"
    chmod 644 "$tmp"
    chown root:root "$tmp" 2>/dev/null || true
    mv "$tmp" "$OVM_POLICY_FILE"
}

policy_set_user() { # policy_set_user <user> <mode>
    is_valid_username "$1" || { log_error "policy_set_user: invalid username"; return 1; }
    is_valid_auth_mode "$2" || { log_error "policy_set_user: invalid mode '$2'"; return 1; }
    _policy_rewrite "$1" "$2"
}

policy_remove_user() { # policy_remove_user <user>
    policy_ready || return 0
    _policy_rewrite "$1" "remove"
}

policy_sync_header() { # re-emit allowed/default lines from config (creates the file)
    _policy_rewrite "" ""
}

policy_noncompliant() { # policy_noncompliant "<allowed modes>" -> "name mode" lines
    local allowed=" $1 " name mode
    while read -r name mode; do
        [[ -z "$name" ]] && continue
        [[ "$allowed" == *" ${mode} "* ]] || echo "${name} ${mode}"
    done < <(policy_list_users)
}

# -----------------------------------------------------------------------------
# PAM gate group synchronisation
# -----------------------------------------------------------------------------

mode_groups() { # mode_groups <mode> -> the gate groups a member of that mode needs
    local m="$1" g=""
    mode_uses_password "$m" && g+="${OVM_GRP_PASSWORD} "
    mode_uses_totp "$m"     && g+="${OVM_GRP_TOTP} "
    mode_uses_yubikey "$m"  && g+="${OVM_GRP_YUBIKEY} "
    printf '%s' "${g% }"
}

policy_sync_groups() { # policy_sync_groups <user> <mode>
    local user="$1" mode="$2" g want
    id -u "$user" >/dev/null 2>&1 || return 0   # cert-only users may have no account
    want=" $(mode_groups "$mode") "
    for g in "$OVM_GRP_PASSWORD" "$OVM_GRP_TOTP" "$OVM_GRP_YUBIKEY"; do
        groupadd -f -r "$g" 2>/dev/null || groupadd -f "$g" 2>/dev/null || true
        if [[ "$want" == *" ${g} "* ]]; then
            id -nG "$user" 2>/dev/null | tr ' ' '\n' | grep -qx "$g" \
                || usermod -aG "$g" "$user"
        else
            id -nG "$user" 2>/dev/null | tr ' ' '\n' | grep -qx "$g" \
                && gpasswd -d "$user" "$g" >/dev/null 2>&1
        fi
    done
    return 0
}

# -----------------------------------------------------------------------------
# Generated helper scripts
# -----------------------------------------------------------------------------

write_policy_script() {
    # The per-connection policy gate. OpenVPN runs it as its UNPRIVILEGED
    # user via 'auth-user-pass-verify ... via-file' - it can read the policy
    # file (0644) but no secrets, and it never reads the password line.
    mkdir -p "$(dirname "$OVM_POLICY_SCRIPT")"
    {
        cat <<EOF
#!/bin/sh
# openvpn-manager: per-user authentication policy gate. FAIL-CLOSED.
# \$1 = temp file from OpenVPN: line 1 = username, line 2 = password.
# The password line is NEVER read here - credentials are verified by PAM
# in a privileged process. Output goes to the OpenVPN journal and never
# contains credentials.
POLICY="${OVM_POLICY_FILE}"
EOF
        cat <<'EOF'
cn="${common_name:-}"
[ -n "$cn" ] || { echo "auth-policy: DENY - no certificate common name"; exit 1; }
[ -r "$POLICY" ] || { echo "auth-policy: DENY cn=$cn - policy file missing or unreadable"; exit 1; }

u=""
if [ -n "${1:-}" ] && [ -r "$1" ]; then
    u="$(head -n 1 -- "$1")"
fi

mode="$(awk -v c="$cn" '$1=="user" && $2==c {print $3; exit}' "$POLICY")"
if [ -z "$mode" ]; then
    echo "auth-policy: DENY cn=$cn - no policy entry for this certificate"
    exit 1
fi

allowed=" $(awk '$1=="allowed" {$1=""; print; exit}' "$POLICY") "
case "$allowed" in
    *" $mode "*) ;;
    *)
        echo "auth-policy: DENY cn=$cn - mode '$mode' is not allowed by the enforcement rules"
        exit 1 ;;
esac

# A username, when sent, must always equal the certificate CN - this binds
# credentials to the certificate and prevents cross-user credential mixing.
if [ -n "$u" ] && [ "$u" != "$cn" ]; then
    echo "auth-policy: DENY cn=$cn - login username does not match the certificate"
    exit 1
fi

if [ "$mode" = "cert" ]; then
    exit 0
fi

if [ -z "$u" ]; then
    echo "auth-policy: DENY cn=$cn - mode '$mode' requires a username/password login"
    exit 1
fi
exit 0
EOF
    } > "$OVM_POLICY_SCRIPT"
    chmod 755 "$OVM_POLICY_SCRIPT"
    chown root:root "$OVM_POLICY_SCRIPT" 2>/dev/null || true
}

write_pam_empty_script() {
    # First line of the generated PAM stack. Certificate-only clients send no
    # credentials; with 'auth-user-pass-optional' OpenVPN still consults PAM,
    # passing EMPTY strings. This helper short-circuits exactly that case to
    # success - WHETHER an empty login is acceptable for the connecting
    # certificate was already enforced (fail-closed) by auth-policy.sh.
    # For any non-empty username it exits 1 and the normal stack continues.
    mkdir -p "$(dirname "$OVM_PAM_EMPTY_SCRIPT")"
    cat > "$OVM_PAM_EMPTY_SCRIPT" <<'EOF'
#!/bin/sh
# openvpn-manager: succeed ONLY for an empty PAM_USER (certificate-only login).
[ -z "${PAM_USER:-}" ] && exit 0
exit 1
EOF
    chmod 755 "$OVM_PAM_EMPTY_SCRIPT"
    chown root:root "$OVM_PAM_EMPTY_SCRIPT" 2>/dev/null || true
}
